### ISSUE TITLE
complex decision tree when computing silicon bands?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#124]
These are the reports when running the `bands` workflow on silicon:

```
Running a PwBandsWorkChain...
08/23/2019 02:04:53 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [189|PwBandsWorkChain|run_relax]: launching PwRelaxWorkChain<191>
08/23/2019 02:04:53 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [191|PwRelaxWorkChain|run_relax]: launching PwBaseWorkChain<194>
08/23/2019 02:04:54 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|run_calculation]: launching PwCalculation<200> iteration #1
08/23/2019 02:07:43 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|_handle_calculation_sanity_checks]: calculation<200> run with smearing and highest band is occupied
08/23/2019 02:07:43 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|_handle_calculation_sanity_checks]: BandsData<203> has invalid occupations: Occupation of 2.0 at last band lkn<0,0,16>
08/23/2019 02:07:43 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|_handle_insufficient_bands]: PwCalculation<200> had insufficient bands
08/23/2019 02:07:43 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|_handle_insufficient_bands]: Action taken: increased the number of bands to 20 and restarting from scratch
08/23/2019 02:07:43 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|inspect_calculation]: PwCalculation<200> finished successfully, but sanity check failed, restarting
08/23/2019 02:07:43 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|run_calculation]: launching PwCalculation<209> iteration #2
08/23/2019 02:10:30 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|inspect_calculation]: PwCalculation<209> completed successfully
08/23/2019 02:10:30 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|results]: work chain completed after 2 iterations
08/23/2019 02:10:30 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [194|PwBaseWorkChain|on_terminated]: remote folders will not be cleaned
08/23/2019 02:10:31 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [191|PwRelaxWorkChain|inspect_relax]: after iteration 1 cell volume of relaxed structure is 163.76340649895988
08/23/2019 02:10:31 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [191|PwRelaxWorkChain|results]: workchain completed after 1 iterations
08/23/2019 02:10:31 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [191|PwRelaxWorkChain|on_terminated]: remote folders will not be cleaned
08/23/2019 02:10:33 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [189|PwBandsWorkChain|run_scf]: launching PwBaseWorkChain<223> in scf mode
08/23/2019 02:10:34 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|run_calculation]: launching PwCalculation<229> iteration #1
08/23/2019 02:11:08 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|_handle_calculation_sanity_checks]: calculation<229> run with smearing and highest band is occupied
08/23/2019 02:11:08 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|_handle_calculation_sanity_checks]: BandsData<232> has invalid occupations: Occupation of 2.0 at last band lkn<0,0,16>
08/23/2019 02:11:08 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|_handle_insufficient_bands]: PwCalculation<229> had insufficient bands
08/23/2019 02:11:08 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|_handle_insufficient_bands]: Action taken: increased the number of bands to 20 and restarting from scratch
08/23/2019 02:11:08 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|inspect_calculation]: PwCalculation<229> finished successfully, but sanity check failed, restarting
08/23/2019 02:11:08 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|run_calculation]: launching PwCalculation<237> iteration #2
08/23/2019 02:11:44 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|inspect_calculation]: PwCalculation<237> completed successfully
08/23/2019 02:11:44 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|results]: work chain completed after 2 iterations
08/23/2019 02:11:44 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [223|PwBaseWorkChain|on_terminated]: remote folders will not be cleaned
08/23/2019 02:11:45 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [189|PwBandsWorkChain|run_bands]: launching PwBaseWorkChain<244> in bands mode
08/23/2019 02:11:46 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [244|PwBaseWorkChain|run_calculation]: launching PwCalculation<247> iteration #1
08/23/2019 02:12:20 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [244|PwBaseWorkChain|inspect_calculation]: PwCalculation<247> completed successfully
08/23/2019 02:12:20 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [244|PwBaseWorkChain|results]: work chain completed after 1 iterations
08/23/2019 02:12:20 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [244|PwBaseWorkChain|on_terminated]: remote folders will not be cleaned
08/23/2019 02:12:21 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [189|PwBandsWorkChain|results]: workchain succesfully completed
08/23/2019 02:12:21 PM <6046> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [189|PwBandsWorkChain|on_terminated]: remote folders will not be cleaned
PwBandsWorkChain<189> terminated with state: finished [0]

Output link               Node pk and type
------------------------------------------------------------
band_parameters           Dict<252> 
band_structure            BandsData<250> 
primitive_structure       StructureData<220> 
scf_parameters            Dict<242> 
seekpath_parameters       Dict<218> 
```

@sphuber @borellim 
A few questions:
 * Why does the highest band have occupation 2.0? Doesn't QE by default add additional bands?
 * When it says `PwCalculation<200> finished successfully, but sanity check failed, restarting`, does this mean it ran a pwcalculation first? Wouldn't it have been straightforward to figure out the occupation beforehand?
 * The same issue appeared again after the relaxation, i.e. it seems it did not remember what occupation was needed
 * The jupyter notebook from the last tutorial took the fermi energy from the `scf_parameters` but now this dictionary does not contain the fermi energy. Why isn't it parsed?

**Comment by sphuber** [comment]
1. QE will use [half the number of electrons for an insulator](https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm250) as the number of bands. Since we do not specify smearing in the inputs, it treats the system as an insulator and no additional bands are added. If you want to prevent this, one can set `occupations=fixed` in the `SYSTEM` card. Since it is not guaranteed that the CLI will always run for an insulator, I do not put it in.
2. Yes it ran a `PwCalculation` and the sanity check triggered because there were clearly too few bands.  Since the `occupations` input was not explicitly set to `fixed`, the workchain assumes that the material is potentially a metal and should be treated as such, therefore the bands are increased. For insulators you could know in advance yes, but for metals you don't know how many empty bands are required.
3. It actually should port over the new number of bands. Which version of `aiida-quantumespresso` are you using?
4. When I run it on `develop` I do get the `fermi_energy` in the `scf_parameters` so not sure why you are not seeing it

**Comment by ltalirz** [comment]
Thanks @sphuber for the detailed replies!

First the replies to 3/4

> It actually should port over the new number of bands. Which version of aiida-quantumespresso are you using?

Ah, great. I'm running the latest `develop` branch: hash 09e8a2c1f10d4a0d994ad2c9dc1f51f56babe558

> When I run it on develop I do get the fermi_energy in the scf_parameters so not sure why you are not seeing it

Thanks for giving this a try! Hm... then perhaps there is something fishy with my install. I wonder what it could be... I will investigate.

**Comment by ltalirz** [comment]
Then, one follow-up question concerning 1/2:

This seems like a slight inconsistency to me - on the one hand you rely on Quantum Espresso to tell you whether the system is an insulator or a metal (and it will increase the bands if it is a metal).
On the other hand, your sanity check always assumes it is a metal (unless specified otherwise), so the sanity check will always trigger if you provide an insulating structure without extra parameters, despite the fact that Quantum Espresso considers the occupations to be fine (and, arguably, they actually are fine - e.g. for the relaxation of Si there is no need to add bands).

I see two ways around this:
 1. Your workflow could add 20% of bands by default from the beginning, irrespective of whether it is a metal or not
 2. At the stage of the sanity check, your workflow could check whether QE added bands and, if not, skip the check on the occupation of the highest band.

**Comment by sphuber** [comment]
Not quite true, I do not rely on Quantum ESPRESSO at all to tell me what it is. In fact QE does not make such a determination. The only thing it does is to add 20% bands to half number electrons if smearing is defined in the input parameters and `nbnd` is not already explicitly defined. That is all. The sanity check is disabled if the input parameters explicitly specify `occupations=fixed`.

The thing here is that the `PwBandsWorkChain` that you ran is a "dumb" work chain. It is still up to the user to specify the input parameters. Typically, if they know they are passing silicon, they should simply specify `occupations=fixed` and the work chain will not do anything. That is exactly how QE "determines" whether something is a metal or not. If smearing is defined it is a metal, otherwise it treats it as an insulator.

What you are looking for is a "turn-key" solution, which is what the `PwBandStructureWorkChain` is. That workchain tries to exactly determine these parameters without user input. However, this is still very much in development. I have slowly been working up from the `PwCalculation` to the `PwBaseWorkChain` to the `PwRelaxWorkChain` but haven't had the time yet to really address physics in the band structure ones.

**Comment by ltalirz** [comment]
>  If smearing is defined it is a metal, otherwise it treats it as an insulator.

Ah, right... I was already wondering what magic is implemented in QE - whether it does some super clever but cheap analysis of the Kohn-Sham matrix to come to this conclusion ;-)

Indeed, I was looking for the "turn-key" workflow and will be very happy to try the `PwBandStructureWorkChain` when it's ready.
For this tutorial it is perfectly fine to specify `occupations=fixed`.

So, do I understand correctly that the job of the `PwBandsWorkchain` is to be more "safe" than what QE would do (which would simply run with #electrons/2 or +20% if smearing) but purposefully leaving out some cleverness in optimization?
The separation of tasks between the `PwBandsWorkChain` and the `PwBandStructureWorkChain` is still not very clear to me... but perhaps there are reasons why both are needed?

P.S. I've checked the aiida-quantumespresso version and the aiida-core version and both are the latest develop versions. I've restarted the daemon. The output of the workflow is as before, and the `scf_parameters` only has the `fermi_energy_units` but not the `fermi_energy` key (see the jupyter notebook I sent for the exact commands).
I wonder what I might be doing wrong...

**Comment by sphuber** [comment]
The design of the work chains and their functions is too much too write down here. Maybe best if we meet/discuss in person next week.

Regarding the fermi energy. It might be the version of pw.x that you are using then. Which version are you using, and did you compile with the special XML output format flag? i.e. are you using new or old XML format?

**Comment by ltalirz** [comment]
> Maybe best if we meet/discuss in person next week.

Yes - thanks for your patience!

> Regarding the fermi energy. It might be the version of pw.x that you are using then. Which version are you using, and did you compile with the special XML output format flag? i.e. are you using new or old XML format?

Ah,  I'm using the latest version 6.4.1 which only supports the XML output format, correct?
I was under the impression that aiida-qe now supports the XML output but maybe I'm wrong?
I can go back to QE 6.3 compiled with the OLDXML flag if that's necessary.
Perhaps @borellim can also answer this

**Comment by sphuber** [comment]
There always was an XML output and there was always support for it. In fact, the parsed output nodes are a combination of information taken from the XML and stdout outputs. Since 6.2, the thing that has changed is the _format_ of the XML output. We have added support for it and it is what the version you are using is using, so it does work. However, I just verified, that with the new XML, the fermi energy is no longer being parsed. I will try and figure out why

**Comment by sphuber** [comment]
The problem seems to be that the fermi energy was parsed from the XML, as it is not printed in the stdout. However, the new XML format (which you are running) no longer prints the fermi energy either. So now there is no way to get it. This then seems more of a problem with QE itself than the parser. If you really need it, it is best to run with a version that has the old XML format

**Comment by sphuber** [comment]
As another option to "solve" the problem of the occupations check. You can use the `-S` flag to specify a tiny smearing. This way, QE will add extra bands and the sanity check will not fail. So something like:
```
aiida-quantumespresso workflow launch pw-bands -X pw-v6.4 -p SSSP_v1.1_efficiency_PBE -s 92 -S mv 0.001
```

This way at least you do not have to change any of the existing code and can use it as is. Downside is that you have to use/explain an extra flag

**Comment by ltalirz** [comment]
> However, the new XML format (which you are running) no longer prints the fermi energy either. So now there is no way to get it. 

Hehe, casually deleting the Fermi energy, I love the QE developers ;-)
I checked and I also can't find any replacement in the XML. Perhaps the idea is that they don't want to provide a Fermi energy if you don't specify any smearing/temperature, since it is not strictly defined?

I guess before they were using (e_hoco + e_luco)/ 2 and those energies are still available
```xml
  <band_structure>
      <lsda>false</lsda>
      <noncolin>false</noncolin>
      <spinorbit>false</spinorbit>
      <nbnd>20</nbnd>
      <nelec>3.200000000000000e1</nelec>
      <num_of_atomic_wfc>32</num_of_atomic_wfc>
      <wf_collected>true</wf_collected>
      <highestOccupiedLevel>2.198912862486575e-1</highestOccupiedLevel>
      <lowestUnoccupiedLevel>2.474630053136812e-1</lowestUnoccupiedLevel>
...
```
We could just compute it ourselves if we like.

> As another option to "solve" the problem of the occupations check. You can use the -S flag to specify a tiny smearing. This way, QE will add extra bands and the sanity check will not fail.

Thanks! I'll think about it but perhaps I prefer fixing the occupations.
Two questions:
 * I hope turning on smearing will bring back the fermi energy? If not, this really is a bug and we need to report it https://gitlab.com/QEF/q-e/issues (we might want to do it anyhow)
 * There is still the issue that the sanity check happens twice in the output above. Is this an issue with QE 6.4.1 only? Perhaps we should open an issue for this?

**Comment by sphuber** [comment]
Yes, putting a smearing will have the XML contain the fermi energy and it will be parsed.

Regarding the sanity check occurring twice. This is because the first time happens in the relaxation part, handled by the `PwRelaxWorkChain`, which does correctly pass along the change, but only for the calculations _it_ manages. The next time occurs in the scf step, which is independent of the `PwRelaxWorkChain` and the `PwBandsWorkChain` does not propagate the change to the next steps. I have to see how it can notice this change and pass it along to the the other workchains it launches. I will open an issue.

**Comment by ltalirz** [comment]
From the tutorial point of view, this issue was fixed by switching to the `PwBandstructure` workchain.
