### ISSUE TITLE
Section 3.4: Submitted calculation does not end up in "Failed" state

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#191]
Following instructions in section 3.4, the calculation submitted to the daemon remains in state *Created* with the following daemon log output:

```
$ verdi daemon logshow 
10/07/2019 12:17:43 PM <12731> aiida.parser.PwParser: [ERROR] ERROR_OUTPUT_STDOUT_INCOMPLETE
10/07/2019 12:17:43 PM <12731> aiida.parser.PwParser: [ERROR] Both the stdout and XML output files could not be read or parsed.
10/07/2019 12:17:43 PM <12731> aiida.parser.PwParser: [ERROR] parser returned exit code<300>: Both the stdout and XML output files could not be read or parsed.
```

This is the process list:
```
$ verdi process list -a -p1
  PK  Created    Process label    Process State    Process status
----  ---------  ---------------  ---------------  ----------------
2061  7m ago     PwCalculation    ⏹ Created

Total results: 1

Info: last time an entry changed state: 7m ago (at 10:17:43 on 2019-10-07)
```

**Comment by csadorf** [comment]
It appears that the process was actually executed, but it does end up in the *failed* state as promised:

```
$ verdi calcjob outputcat 2061
-
     Program PWSCF v.6.4.1 starts on  7Oct2019 at 12:17:33 

     This program is part of the open-source Quantum ESPRESSO suite
     for quantum simulation of materials; please cite
         "P. Giannozzi et al., J. Phys.:Condens. Matter 21 395502 (2009);
         "P. Giannozzi et al., J. Phys.:Condens. Matter 29 465901 (2017);
          URL http://www.quantum-espresso.org", 
     in publications or presentations arising from this work. More details at
     http://www.quantum-espresso.org/quote

     Parallel version (MPI), running on     2 processors

     MPI processes distributed on     1 nodes
     R & G space division:  proc/nbgrp/npool/nimage =       2
     Reading input from aiida.in

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine  read_namelists (1):
      bad line in namelist &system: "  mickeymouse =   2.4000000000d+02" (error could be in the previous line)
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by ltalirz** [comment]
I think also this is fixed in `develop` - right @sphuber ?
...

**Comment by sphuber** [comment]
I am not a 100% sure. There was indeed a problem causing submitted calculations to get stuck in `Created`, however, this was related to entry points not being available to the daemon. This bug was fixed, but in this example it seems that the daemon was actually able to pick it up and start running.

Ah no, never mind, I remember. There was a second bug that caused attributes to be overridden when setting extras on the node from the shell in which it was submitted. This was for the Django backend and also has been fixed. So yes, this problem should have been fixed in develop

**Comment by CasperWA** [comment]
So to get this fix in, we would either need to build a new VM image or go through all machines and update them to the newest `develop` version of AiiDA - or perhaps a specific commit?

**Comment by ltalirz** [comment]
For tutorial purposes, I would certainly recommend locking to a particular commit (e.g. the current latest one from `develop`).
"Building" an image is actually very simple - you simply start a VM from the old image, make the change and take a snapshot.

If you've started all VMs for the tutorial already, that's of course some work... up to you!

**Comment by CasperWA** [comment]
I will answer @sphuber's [comment/question](https://github.com/aiidateam/aiida-tutorials/issues/187#issuecomment-539082123) here as well, I think.

@yakutovicha will start them at the earliest time tomorrow evening, so there would be time to do what you suggest @ltalirz.
The tutorial starts Wednesday at 10 am (the time here), 6:30 am CET.

**Comment by sphuber** [comment]
Alternatively, you could change the documentation. The problematic line is where they set an extra on the calculation node after having submitted it. If you remove that line from the docs, the bug won't be triggered. At least not there in any case ;)

**Comment by CasperWA** [comment]
Fair enough. But I think I have convinced @yakutovicha to update aiida-core to the latest develop, install critical Ubuntu updates and a snapshot of that should be good for deployment tomorrow evening/Wednesday morning.

**Comment by hududed** [comment]
Hello

Following up on this problem.

I followed @sphuber 's suggestion to not run `calculations.set_extra` and job did not finish with a non-zero number, but now with this error:

`Critical: Could not contact Circus to get the number of active workers`

**Comment by ltalirz** [comment]
Hi @hududed , this sounds to me like an issue with the AiiDA daemon / rabbitmq.
What does `verdi status` show? If there is an issue with rabbitmq, what is `sudo service rabbitmq-server status`?
Have you tried `verdi daemon restart`?

**Comment by ltalirz** [comment]
Hi @hududed, there were a few issues in the setup of QM 20.03.0 (see https://github.com/marvel-nccr/quantum-mobile/issues/113) which is why we released 20.03.1 right thereafter.

One of the fixed issues was an upgrade to aiida-quantumespresso v3.0.0a6 which should fix the issue you observed.
Instead of downloading the new machine, you can simply `pip install aiida-quantumespresso==3.0.0a6` inside the aiida virtual environment.

**Comment by sphuber** [comment]
The job finished correctly (from AiiDA's perspective) but with a non-zero exit code, saying there was an actual problem with the calculation output. You can run `verdi plugin list aiida.calculations quantumespresso.pw` to see the explanation of the various exit codes. When you look up `322` which is the exit code you got, you will see that the output XML had an unsupported format. This is probably because QE 6.5 was run and this was not yet supported. As @ltalirz said the latest version of QM has an updated version of the plugin which _does_ support the new version

**Comment by hududed** [comment]
Thanks @ltalirz @sphuber it works now!
