### ISSUE TITLE
👌 IMPROVE: Use the `aiida-pseudo` package for installing pseudos

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-tutorials#215]
This would avoid to run these lines (see #214):
```bash
mkdir sssp_pseudos
wget 'https://archive.materialscloud.org/record/file?filename=SSSP_1.1_PBE_efficiency.tar.gz&record_id=23&file_id=d2ce4186-bf76-4e05-8b39-444b4da30273' -O SSSP_1.1_PBE_efficiency.tar.gz
tar -C sssp_pseudos -zxvf SSSP_1.1_PBE_efficiency.tar.gz
verdi data upf uploadfamily sssp_pseudos 'SSSP' 'SSSP pseudopotential library'
```
@sphuber is the package ready? What would be the equivalent commands? @chrisjsewell is it already in the quantum mobile?

**Comment by chrisjsewell** [comment]
> is it already in the quantum mobile?

Not at present. This relates to https://github.com/marvel-nccr/ansible-role-aiida/issues/35

**Comment by sphuber** [comment]
It currently is working, see master branch: https://github.com/aiidateam/aiida-pseudo/commits/master
But I haven't released it yet, because I haven't had the time to discuss with other developers about the design/naming choices etc. Also some advanced functionality that was in `aiida-sssp`, i.e. to automatically get the cutoffs for a given structure, have not yet been ported. Also, depending on how it is used, it might require an update of `aiida-quantumespresso`.

**Comment by chrisjsewell** [comment]
I believe the answer is no then for the coming tutorial, so I've changed the name of this issue as a reminder for the next tutorial

**Comment by ltalirz** [comment]
Would people agree to replace these 4 commands with a simple import?
```
verdi import -n "https://archive.materialscloud.org/record/file?file_id=2a59c9e7-9752-47a8-8f0e-79bcdb06842c&record_id=23&filename=SSSP_1.1_PBE_efficiency.aiida"
```

Perhaps this section 2.2.4 can also be deleted entirely and the pseudopotential import moved to a place where it is needed (not sure people need to see this before starting to run their first calculation).

**Comment by sphuber** [comment]
That will import the pseudos, but that won't work with the rest of the tutorial. The tutorial relies on a group of type `core.upf` existing with the name `sssp_pseudos`, but the import will create just a group with a randomly generated name and of type `core.import`. You can use `-G sssp_pseudos` to get the correct name, but you cannot influence the type. This is important because for example the command in section 3.4.2. will then not show any families. So unfortunately, we cannot simplify this at the moment

**Comment by ltalirz** [comment]
Ok, thanks for the clarification.

**Comment by mbercx** [comment]
Indeed, very important to check this. @ramirezfranciscof I think this will be done first in the "Running calculations" section?

**Comment by ltalirz** [comment]
pseudo setup via `aiida-pseudo` was added in https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/sections/running_processes/basics.html#structure-and-pseudopotentials
