### ISSUE TITLE
basics: takes >1h before running your first calculation

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#242]
This may be something for the 2021 edition of the tutorial, but after going through the "basics" section, I have to say that this is a very long way for anyone before they ever get to run any calculations themselves, with lots of details, e.g. on kpoints, upfdata etc. that won't matter to many folks.

Admittedly, this is how we started the May tutorial last year that I organized (mea culpa), but we realized this issue and the "first taste" section (as e.g. [here](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_SINTEF/sections/first_taste.html)) was created for exactly this reason and used in a number of later tutorials
In a virtual tutorial, where people are less committed to stay, getting to the point quickly is even more important than in a physical one.

An alternative route than the "First taste" would start with the "Basic Tutorial" from the documentation, and then add bits and pieces where necessary.

It's too late to change this now, but let's keep this in mind next time @giovannipizzi @mbercx @chrisjsewell @csadorf @sphuber

**Comment by sphuber** [comment]
I have always voiced this opinion as well and I would actually start with the basic tutorial from the documentation. It does not contain any unnecessary domain specific details, it is doable in less than an hour and it shows a large part of interesting AiiDA features with no need for boring setup and configuration steps. For me this hits all the checkmarks. Afterwards we can then lure people to do more "interesting" real-life calculations.

But not sure if we will have the time to still do this in a timely fashion.

**Comment by csadorf** [comment]
I remember distinctly that the ability to use the basic tutorial as starting point for our extended tutorials was a clear criterion for its design. In so far, in favor of that.

**Comment by mbercx** [comment]
I agree that starting with the basic tutorial from the documentation is a good idea. I think I quickly discussed this with @giovannipizzi a few weeks ago, but at that time we decided to stick with the previous version since topics such as kpoints/upfdata are used later in the tutorial, so we'd have to do a rather large overhaul to integrate the basic tutorial from the documentation with the one for the virtual tutorial.

I don't mind having a crack at this today, though. I.e. first test the basic tutorial from the docs on the VM and then start the virtual tutorial with this one, and add the pieces which we need for the rest of the sections.

**Comment by ltalirz** [comment]
> I don't mind having a crack at this today, though. I.e. first test the basic tutorial from the docs on the VM and then start the virtual tutorial with this one, and add the pieces which we need for the rest of the sections.

It could make a quite significant difference, so if you manage to find the time, I think it is worth a try.
I'll be happy to re-check if you open a PR.

**Comment by mbercx** [comment]
This has been fixed in #245.
