### ISSUE TITLE
tutorial web page "jumps" in between copy-paste

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#246]
I've experienced a number of times that when using the "copy" button to copy code, then pasting it in the terminal, and then returning to the tutorial web page (clicking on it to get it back into focus), the web page jumps (scrolls) to a different place in the page.

It does not happen every time, and I still haven't managed to nail down properly what exactly causes it - just posting this here to see whether others have encountered the same issue.

This is with Google Chrome 83.0 on MacOS 10.15.5

**Comment by chrisjsewell** [comment]
I would report this in executablebooks/sphinx-copybutton

**Comment by mbercx** [comment]
I've also experienced this. Note how the jump only happens if I scroll down after I copy:

![out](https://user-images.githubusercontent.com/25607960/100037188-ed89ad00-2e01-11eb-9539-bb8c13ef1750.gif)

Whether I scroll before or after I switch back between windows doesn't matter. So "copy -> switch to terminal -> scroll on page while terminal is selected -> select chrome" has the same effect (and is more common).

I'll open an issue with executablebooks/sphinx-copybutton tomorrow. 😴

**Comment by mbercx** [comment]
Closing since this is an issue on executablebooks/sphinx-copybutton.
